### ISSUE TITLE
Wrap width action 

### ISSUE THREAD

**Issue by jordanjanaq** [chnouman/AwesomeDialog#3]
Hi, nice library. I've tested the sample and get differente width for positive and negative buttons. And i'd like to make them like your example
<img width="354" alt="Captura de Pantalla 2020-11-12 a la(s) 16 58 41" src="https://user-images.githubusercontent.com/48919342/99001127-53c02700-2508-11eb-8aa0-b3b970809c0d.png">

**Comment by chnouman** [comment]
@jordanjanaq thank you for your support. Please use this updated version and let me know if you still face issue.

`implementation 'com.github.chnouman:AwesomeDialog:1.0.5'`

**Comment by chnouman** [comment]
The issue is resolved.
